trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@1
  displayName: 'Checkout code'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
  displayName: 'Set up JDK 11'

- script: mvn clean package
  displayName: 'Build with Maven'

- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'DockerHubServiceConnection'
  displayName: 'Log in to Docker Hub'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'sharmapiyush0402/demo'
    dockerfile: '**/Dockerfile'
    tags: |
      - latest
      - $(Build.BuildId)
  displayName: 'Build and push Docker image'
