trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout code'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'  # Use 'PreInstalled' for the source option
  displayName: 'Set up JDK 11'

- script: mvn clean package
  displayName: 'Build with Maven'

- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'DockerHubServiceConnection'  # Ensure this is the correct service connection name
  displayName: 'Log in to Docker Hub'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'sharmapiyush0402/demo'
    dockerfile: 'Dockerfile'  # Adjust this if your Dockerfile is in a different location
    tags: |
      latest
      $(Build.BuildId)
  displayName: 'Build and push Docker image'