trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  displayName: 'Checkout code'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'  # Use 'PreInstalled' for the source option
  displayName: 'Set up JDK 11'

- script: mvn clean package
  displayName: 'Build with Maven'

- script: |
    REPO_NAME=$(echo $(Build.Repository.Name) | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-')
    BRANCH_NAME=$(echo $(Build.SourceBranchName) | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-')
    echo "##vso[task.setvariable variable=SANITIZED_REPO_NAME]$REPO_NAME"
    echo "##vso[task.setvariable variable=SANITIZED_BRANCH_NAME]$BRANCH_NAME"
  displayName: 'Sanitize repository and branch names'

- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'DockerHubServiceConnection'  # Ensure this is the correct service connection name
  displayName: 'Log in to Docker Hub'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'sharmapiyush0402/demo'
    dockerfile: 'Dockerfile'  # Adjust this if your Dockerfile is in a different location
    tags: |
      $(SANITIZED_REPO_NAME):$(SANITIZED_BRANCH_NAME)-1.0.$(Build.BuildId)
  displayName: 'Build and push Docker image'