trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@1
  displayName: 'Checkout code'

- task: JavaToolInstaller@1
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: mvn clean package
  displayName: 'Build with Maven'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Using DockerHubCredentials library"
  displayName: 'Use DockerHubCredentials library'

- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'DockerHubServiceConnection'
    dockerRegistryEndpoint: 'DockerHubServiceConnection'
  displayName: 'Log in to Docker Hub'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: 'sharmapiyush0402/demo'
    dockerfile: '**/Dockerfile'
    tags: |
      $(Build.SourceBranchName)
  displayName: 'Build and push Docker image' 
