name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean package

    - name: Execute Test Cases
      run: mvn test

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image for Microservice 1 to ACR
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/microservice1:1.0.${{ github.run_number }} -f microservice1/Dockerfile .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/microservice1:1.0.${{ github.run_number }}

    # Repeat the above steps for each additional microservice
    - name: Build with Maven
      run: mvn clean package -f microservice2/pom.xml

    - name: Execute Test Cases
      run: mvn test -f microservice2/pom.xml

    - name: Build and push Docker image for Microservice 2 to ACR
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/microservice2:1.0.${{ github.run_number }} -f microservice2/Dockerfile .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/microservice2:1.0.${{ github.run_number }}
