properties:
  template:
    containers:
      - name: backend
        image: ${{ secrets.ACR_LOGIN_SERVER }}/backend:${{ github.ref_name }}-${{ github.run_id }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
