name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn test

      - name: Get the current version
        id: get_version
        run: echo ::set-output name=version::$(git describe --tags --abbrev=0)

      - name: Increment version
        id: increment_version
        run: |
          current_version=${{ steps.get_version.outputs.version }}
          IFS='.' read -r -a version_parts <<< "$current_version"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          echo "New version: $new_version"
          echo ::set-output name=new_version::$new_version

      - name: Create new tag
        run: |
          new_version=${{ steps.increment_version.outputs.new_version }}
          git tag $new_version
          git push origin $new_version

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/my-app:${{ steps.increment_version.outputs.new_version }} .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-app:${{ steps.increment_version.outputs.new_version }}
